use_calib: False
# used_dataset: "datasets/tum/rgbd_dataset_freiburg1_desk"
used_dataset: "datasets/replica/office2"
# used_dataset: "datasets/replica/office1"
# used_dataset: "datasets/replica/office3"
# used_dataset: "datasets/replica/room0"

stop_at_frame: 1000000
stop_at_keyframe: 5
run_backend: True
run_gaussian_optimizer: True
gaussians:
  init_lr: 0.05 #6.0
  num_iterations: 0
  window_size: 11 # 2 newest frames are subtracted -> window_size = 2 newest frames + N random frames
  tracking_itr_num: 100
  c_conf_threshold: 1.5
  use_matching_mask: True
  l1_mask: False
  l1_threshold: 0.1
  # densify_at_it_nr: [10, 20]
  pre_pose_optimization: False
  post_pose_optimization: False
  seed: 0
  pipeline_params:
    convert_SHs_python: False
    compute_cov3D_python: False
  tracking_lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001
  rgb_boundary_threshold: 0.01
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01
  alpha: 0.9 # fraction of rgb in rgbd loss
  rgb_boundary_threshold: 0.01
  # init_gaussian_th: 0.005
  gaussian_th: 0.7
  # init_gaussian_extent: 30
  gaussian_extent: 1.0
  size_threshold: 20
  prune_window_size: 3
  prune_mode: "slam"
  map_optimisation_params:
    iterations: 30000
    position_lr_init: 0.0016
    position_lr_final: 0.0000016
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001
    rotation_lr: 0.001
    percent_dense: 0.01
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002

single_thread: False

dataset:
  subsample: 1
  img_downsample: 1
  center_principle_point: True

matching:
  max_iter: 10
  lambda_init: 1e-8
  convergence_thresh: 1e-6
  dist_thresh: 1e-1 # distance in 3D space
  radius: 3
  dilation_max: 5 # Right now starts from max and iteratively decreases until 1

tracking:
  min_match_frac: 0.05
  max_iters: 50
  C_conf: 0.0
  Q_conf: 1.5
  rel_error: 1e-3
  delta_norm: 1e-3
  huber: 1.345
  match_frac_thresh: 0.333
  sigma_ray: 0.003
  sigma_dist: 1e+1
  sigma_pixel: 1.0
  sigma_depth: 1e+1 # NOTE: log-depth!
  sigma_point: 0.05
  pixel_border: -10 # Only in calib (negative means allow pixels outside image up to that distance)
  depth_eps: 1e-6 # Only in calib case
  filtering_mode: weighted_pointmap # recent, first, best_score, weighted_pointmap, weighted_spherical, indep_conf
  filtering_score: median # median, mean (only used for filtering_mode=best_score)

local_opt:
  pin: 1
  window_size: 1e+6   
  C_conf: 0.0
  Q_conf: 1.5
  min_match_frac: 0.1
  pixel_border: -10 # Only in calib (negative means allow pixels outside image up to that distance)
  depth_eps: 1e-6 # Only in calib case
  max_iters: 10
  sigma_ray: 0.003
  sigma_dist: 1e+1
  sigma_pixel: 1.0
  sigma_depth: 1e+1 # NOTE: log-depth!
  sigma_point: 0.05
  delta_norm: 1e-8
  use_cuda: True

retrieval:
  k: 3
  min_thresh: 5e-3

reloc:
  min_match_frac: 0.3
  strict: True